### PR TITLE
Add Event Section

### PR DESCRIPTION
**Pull request by natesabrown**
Added an "Events" section that makes a component for listing out past and future events for CFD

### CODE REVIEW

**Comment by anthony-zhou** [comment]
@natesabrown Looks great! It just might be a little disorienting for the images to shrink so much on hover. Do you think we should make it a bit less drastic? Thanks.

Edit: another option would be to make the images grow larger on hover.

**Comment by natesabrown** [comment]
> @natesabrown Looks great! It just might be a little disorienting for the images to shrink so much on hover. Do you think we should make it a bit less drastic? Thanks.
> 
> Edit: another option would be to make the images grow larger on hover.

Yeah, I made them shrink so that if the user wants to see stuff that is hidden by the graphic they could have the option. I'll change the degree of shrinkage and if that's still disorienting we can switch to another approach

**Comment by anthony-zhou** [comment]
What graphics are you referring to? I'm not sure I understand what's getting hidden.

**Comment by natesabrown** [comment]
Kapture 2020-06-08 at 16 26 06



The text of some of the images being hidden upon browser resize (as can be seen in the "Open Data Day" card in the gif above). I thought a fixed-height image would be a better sacrifice than making the height variable and leaving empty space in the card, so I wanted the users to be able to size the image down on hover so they could intuitively see the full image without too much of a hassle.

**Comment by anthony-zhou** [comment]
Oh I see. Is there any way to just make the card height automatically match the content within it? That way there would be no empty space and it'd be responsive too.

**Comment by natesabrown** [comment]
To make the card height automatically match the content would change the current design aesthetic from fixed-height cards to variable-height cards, if I’m understanding what you’re suggesting. Personally, I feel like that adds more mental overhead/cognitive load to the user, as it increases the unpredictability of the element (see Google Keep layout vs. Google Docs document preview). Given that images have a large variability in height, that would almost definitely leave an overhang at the end of the grid when there are more than 1 items per row. I attached a drawing meant to illustrate what I’m talking about.

A possible solution for this is to add variable height cards but make a fixed-height background (extending past the width of the sub-container, similar to the “We are code for dallas” introduction component), which would imply containerization but allow for variable height cards.

I prefer the fixed-height cards with media-queries/size decrease/increase to account for the images because I think that design is more mature. Obviously this comes down to personal preference, and a website should not be torn in two between two aesthetic preferences, so I would appreciate a decision between the three options (fixed-height variable images, variable-height according to images, or variable-height with shaded background) and I’ll implement it.

**Comment by natesabrown** [comment]
> To make the card height automatically match the content would change the current design aesthetic from fixed-height cards to variable-height cards, if I’m understanding what you’re suggesting. Personally, I feel like that adds more mental overhead/cognitive load to the user, as it increases the unpredictability of the element (see Google Keep layout vs. Google Docs document preview). Given that images have a large variability in height, that would almost definitely leave an overhang at the end of the grid when there are more than 1 items per row. I attached a drawing meant to illustrate what I’m talking about. A possible solution for this is to add variable height cards but make a fixed-height background (extending past the width of the sub-container, similar to the “We are code for dallas” introduction component), which would imply containerization but allow for variable height cards. I prefer the fixed-height cards with media-queries/size decrease/increase to account for the images because I think that design is more mature. Obviously this comes down to personal preference, and a website should not be torn in two between two aesthetic preferences, so I would appreciate a decision between the three options (fixed-height variable images, variable-height according to images, or variable-height with shaded background) and I’ll implement it.
> […](#)
> On Jun 8, 2020, 4:38 PM -0500, Anthony Zhou ***@***.***>, wrote: Oh I see. Is there any way to just make the card height automatically match the content within it? That way there would be no empty space and it'd be responsive too. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

IMG_0503

**Comment by anthony-zhou** [comment]
Thanks so much for the thorough explanation. What you're saying makes a lot of sense. I agree we should use fixed-height cards, but I wonder if we could just make the cards fixed-dimensions in general. Then at a certain width they would switch from side-by-side to one on top of the other. What do you think of doing that?

**Comment by natesabrown** [comment]
Sure. So does side-by-side mean a carousel? And I’m also assuming that the cards scroll from side-to-side (in a carousel) when the device is small, and transform into the traditional grid view when the device is larger, to take advantage of the increased capacity of the computer screen. I think the breakpoint could be phones/small tablets have the carousel and large tablets/PCs have the grid view. If I’m not correctly understanding you, please let me know.

I’m assuming you are envisioning a carousel because the grid nature of the component already enables it to switch from “side by side” in a sense to directly on top of each other.

**Comment by natesabrown** [comment]
Wait actually I see what you're saying. Just make a well-defined component size and use the grid to change the way they stack while maintaining the same dimensions. That way we can maintain the image consistently and parts of it don't get cut off. No need for a carousel (though depending on how many events get added to this section we might eventually need something like that).

**Pull request closed without merging**
